site_name: Xoomia Help Center
site_description: Xoomia Health Help Center
site_url: https://xoomia.github.io/xoomia-help-center/

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Documentation:
      - Incident Reports: documentation/incident-reports.md

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
